name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Install pnpm globaly
        run: npm install -g pnpm
      - name: Install pnpm
        run: pnpm install
      - name: Lint affected
        run: pnpm nx affected -t lint
      - name: Test affected
        run: pnpm nx affected -t test --configuration=ci
      - name: Build affected
        run: pnpm nx affected -t build
